name: Uni Notice Board CI

on:
  pull_request:
    branches: [ "develop" ]
  push:
    branches: [ "main" ]

jobs:
  lint_job:
    name: Lint (HTMLHint + Stylelint)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Lint HTML Files
        run: npm run lint:html

      - name: Lint CSS Files
        run: npm run lint:css


  build_job:
    name: Build Website (Parcel)
    runs-on: ubuntu-latest
    needs: lint_job

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Website
        run: npm run build


  image_build_job:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    needs: build_job

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t khfaheem/uni-notice-board .

      - name: Push Docker Image
        run: docker push khfaheem/uni-notice-board
